{
  "description": "A cylindrical male connector pin 10mm long and 5mm diameter with a 2mm diameter groove near the base for retaining rings.",
  "code": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(2.5)\n    .extrude(10)\n    .faces(\">Z\")\n    .workplane(centerOption=\"CenterOfMass\")\n    .circle(3)\n    .cutThruAll()\n    .faces(\">Z\")\n    .workplane(offset=-2)\n    .circle(1)\n    .cutBlind(-0.5)\n)",
  "id": "synthetic_4",
  "source": "synthetic",
  "category": "connectors",
  "prompt": "A cylindrical male connector pin 10mm long and 5mm diameter with a 2mm diameter groove near the base for retaining rings."
}