{
  "metrics": {
    "exact_match": 0.0,
    "bleu": 0,
    "execution_success": 0.0,
    "total": 10
  },
  "examples": [
    {
      "prompt": "A storage tank with a radius of 1500mm, a height of 4000mm, and 10mm wall thickness, featuring a hemispherical domed top.",
      "reference": "",
      "prediction": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(750)  # Outer radius 1500mm / 2\n    .circle(740)  # Inner radius 1400mm / 2\n    .extrude(4000)  # Height 4000mm\n    .faces(\">Z\")\n    .workplane()\n    .circle(750)  # Top hemisphere radius\n    .extrude(100)  # Thickness 10mm\n)\n\n# Note: CadQuery does not have a hemisphere primitive, so above code approximates hemisphere with a ring and extrusion\n\n# Alternatively, use the Sphere method from CadQuery math module\n\nimport cadquery as cq\nimport math\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(750)  # Outer radius 1500mm / 2\n    .circle(740)  # Inner radius 1400mm / 2\n    .extrude(4000)  # Height 4000mm\n    .faces(\">Z\")\n    .workplane()\n    .circle(750)  # Top hemisphere radius\n    .extrude(100)  # Thickness 10mm\n)\n\n# More accurate hemisphere using sphere and cut\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(750)  # Outer radius 1500mm / 2\n    .circle(740)  # Inner radius 1400mm / 2\n    .extrude(4000)  # Height 4000mm\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .cutThruAll()\n)\n\n# More accurate hemisphere using sphere and shell\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(4000)  # Height 4000mm\n    .faces(\">Z\")\n    .shell(-100)  # Thickness 10mm wall\n)\n\n# Hollow hemisphere using shell\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n)\n\n# Hollow hemisphere using shell and cut\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .cutThruAll()\n)\n\n# Hollow hemisphere using shell and cut (simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .cut()\n)\n\n# Hollow hemisphere using shell and cut (shell method)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-100)  # Thickness 10mm shell on hemisphere\n)\n\n# Hollow hemisphere using shell and cut (shell method, simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-100)  # Thickness 10mm shell on hemisphere\n)\n\n# Hollow hemisphere using shell and cut (shell method, simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-100)  # Thickness 10mm shell on hemisphere\n)\n\n# Hollow hemisphere using shell and cut (shell method, simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-100)  # Thickness 10mm shell on hemisphere\n)\n\n# Hollow hemisphere using shell and cut (shell method, simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-100)  # Thickness 10mm shell on hemisphere\n)\n\n# Hollow hemisphere using shell and cut (shell method, simplified)\n\nresult = (\n    cq.Workplane(\"XY\")\n    .sphere(500)  # Outer radius 1500mm / 2\n    .shell(-100)  # Thickness 10mm wall\n    .faces(\">Z\")\n    .workplane()\n    .sphere(500)  # Hemisphere radius 750mm\n    .extrude(100)  # Thickness 10mm\n    .edges(\">Z and circle\")\n    .shell(-"
    },
    {
      "prompt": "A piping manifold with a central pipe (dia 200mm) and four perpendicular branch pipes (dia 100mm) spaced 500mm apart.",
      "reference": "",
      "prediction": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(100)  # central pipe radius\n    .extrude(20)  # central pipe length\n    .faces(\">Z\")\n    .workplane()\n    .rect(500, 500, forConstruction=True)  # rectangle for branch pipe placement\n    .vertices()\n    .circle(50)  # branch pipe radius\n    .extrude(20)  # branch pipe length\n)\n\n# Add piping gaps with the 'workplane' pattern\ngap_length = 40\ngap_width = 40\nnum_gaps = 4\n\ngap = (\n    cq.Workplane(\"XY\")\n    .center(-250, 0)\n    .rect(gap_length, gap_width)\n    .extrude(20)\n)\n\nresult = result.union(\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .rect(500, 500, forConstruction=True)\n    .vertices()\n    .workplane(offset=0)\n    .center(-250, 0)\n    .rect(gap_length, gap_width)\n    .extrude(20)\n    .edges(\">Z and >X\")\n    .patternCircular(num_gaps, 0, 0, 0, 0)\n)\n\n# Cut the gaps from the central pipe\nresult = result.cut(\n    cq.Workplane(\"XY\")\n    .center(-250, 0)\n    .rect(gap_length, gap_width)\n    .extrude(20)\n)\n\n# Hollow out the central pipe\nresult = result.faces(\">Z\").workplane().circle(50).cutThruAll()\n\n# Add a small flange at the bottom for mounting\nflange_radius = 120\nflange_thickness = 5\n\nresult = (\n    result.faces(\"<Z\").workplane()\n    .circle(flange_radius)\n    .extrude(flange_thickness)\n)\n\n# Add bolt holes on the flange\nbolt_circle_radius = 110\nnum_bolts = 4\nbolt_hole_diameter = 8\n\nresult = result.faces(\"<Z\").workplane(offset=flange_thickness / 2)\n.polarArray(bolt_circle_radius, 0, 360, num_bolts)\n.hole(bolt_hole_diameter)\n\n# Add a small chamfer on the top edges of the pipes\nresult = result.edges(\">Z and (outer or inner)\").chamfer(2)\n\n# Add fillet to the gap edges\nresult = result.edges(\">Z and (outer or inner)\").fillet(2)\n\n# Add small chamfer on the flange edges\nresult = result.faces(\"<Z\").edges(\">Z\").chamfer(1)\n\n# Add small fillet to the flange edges\nresult = result.faces(\"<Z\").edges(\">Z\").fillet(1)\n\nresult\n\n# Cleaned up final shape\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(100)  # central pipe radius\n    .extrude(20)  # central pipe length\n    .faces(\">Z\")\n    .workplane()\n    .rect(500, 500, forConstruction=True)  # rectangle for branch pipe placement\n    .vertices()\n    .circle(50)  # branch pipe radius\n    .extrude(20)  # branch pipe length\n    # Add piping gaps with the 'workplane' pattern\n    .faces(\">Z\")\n    .workplane()\n    .rect(500, 500, forConstruction=True)\n    .vertices()\n    .workplane(offset=0)\n    .center(-250, 0)\n    .rect(40, 40)\n    .extrude(20)\n    .edges(\">Z and >X\")\n    .patternCircular(4, 0, 0, 0, 0)\n    # Cut the gaps from the central pipe\n    .cut(\n        cq.Workplane(\"XY\")\n        .center(-250, 0)\n        .rect(40, 40)\n        .extrude(20)\n    )\n    # Hollow out the central pipe\n    .faces(\">Z\").workplane().circle(50).cutThruAll()\n    # Add a small flange at the bottom for mounting\n    .faces(\"<Z\").workplane().circle(120).extrude(5)\n    # Add bolt holes on the flange\n    .faces(\"<Z\").workplane(offset=5).polarArray(110, 0, 360, 4).hole(8)\n    # Add chamfer to edges\n    .edges(\">Z and (outer or inner)\").chamfer(2)\n    .faces(\"<Z\").edges(\">Z\").chamfer(1)\n    .edges(\">Z and (outer or inner)\").fillet(2)\n    .faces(\"<Z\").edges(\">Z\").fillet(1)\n)\n\nresult.val()\n\n# Export to STL\nresult.val().save(\"piping_manifold.stl\")\n\n# Preview in browser\nresult\n```\n\n<div class=\"result\"><img src=\"piping_manifold.png\" width=\"600\"/></div>\n\n### Create a simple L-shaped pipe with 50mm outer diameter, 40mm inner diameter, and 100mm length\n\n```python\nimport cadquery as cq\n\n# Outer diameter 50mm\n# Inner diameter 40mm\n# Length 100mm\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(25)  # outer radius\n    .circle(20)  # inner radius\n    .extrude(100)\n    .faces(\">Z\")\n    .workplane()\n    .center(0, 50)\n    .circle(20)\n    .cutThruAll()\n)\n\nresult.val()\n```\n\n<div class=\"result\"><img src=\"simple_pipe.png\" width=\"200\"/></div>\n\n### Create a pipe with a hollow center and a flange at the base\n\n```python\nimport cadquery as cq\n\n# Outer diameter 50mm\n# Inner diameter 40mm\n# Length 100mm\n# Flange diameter 70mm\n# Flange thickness 5mm\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(25)  # outer radius\n    .circle(20)  # inner radius\n    .extrude(100)\n    .faces(\"<Z\")\n    .workplane()\n    .circle(35)  # flange radius\n    .extrude(5)\n)\n\nresult.val()\n```\n\n<div class=\"result\"><img src=\"pipe_flange.png\" width=\"200\"/></div>\n\n### Create a pipe with a hollow center and a flange at the base, including bolt holes on the flange\n\n```python\nimport cadquery as cq\n\n# Outer diameter 50mm\n# Inner diameter 40mm\n# Length 100mm\n# Flange diameter 70mm\n# Flange thickness 5mm\n# Bolt hole diameter 8mm\n# Bolt circle radius 35mm\n# Number of bolt holes 4\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(25)  # outer radius\n    .circle(20)  # inner radius\n    .extrude(100)\n    .faces(\"<Z\")\n    .workplane()\n    .circle(35)  # flange radius\n    .extrude(5)\n    .faces(\"<Z\")\n    .workplane(offset=5)\n    .polarArray(35,"
    },
    {
      "prompt": "A precision CNC tooling plate 300x300x25mm with a grid of 16 holes (dia 10mm) spaced 50mm apart, and filleted edges r=10mm.",
      "reference": "",
      "prediction": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(300, 300, 25)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n    .faces(\">Z\")\n    .workplane()\n    .rarray(16, 16, 50, 50)\n    .hole(10)\n)\n\n# Note: CadQuery's built-in rarray function does not support non-uniform spacing, so a custom pattern is used here\n\nhole_count = 16\nhole_dia = 10\ngrid_size = 50\nplate_thickness = 25\nplate_length = 300\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# For simplicity, the polarArray function above is replaced with a simple loop\n\nholes = []\nfor angle in range(0, 360, 27):\n    holes.append(cq.Workplane(\"XY\").center(grid_size / 2, grid_size / 2).polarLine(grid_size / 2, angle).vertices())\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .pushPoints(holes[0])\n    .hole(hole_dia)\n    .union(\n        cq.Workplane(\"XY\")\n        .workplane(offset=0)\n        .polarArray(grid_size / 2, 0, 360, hole_count)\n        .hole(hole_dia)\n    )\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# A better approach: create a single polygon with holes and cut it\n\nresult = (\n    cq.Workplane(\"XY\")\n    .rect(plate_length, plate_length)\n    .extrude(plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# But this is not ideal: polarArray creates non-uniform holes, so we need to create a better pattern\n\n# Create a single hole pattern\nhole_pattern = (\n    cq.Workplane(\"XY\")\n    .center(0, 0)\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n)\n\n# Cut the hole pattern from a plate\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .cut(hole_pattern)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Note: filleting on the top face is optional\n\n# Instead, fillet on the outer edge\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Or, slightly simpler:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Note: filleting on the top face is optional\n\n# Instead, fillet on the outer edge\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Or, slightly simpler:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Note: filleting on the top face is optional\n\n# Instead, fillet on the outer edge\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Or, slightly simpler:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Note: filleting on the top face is optional\n\n# Instead, fillet on the outer edge\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Or, slightly simpler:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(plate_length, plate_length, plate_thickness)\n    .faces(\">Z\")\n    .workplane()\n    .polarArray(grid_size / 2, 0, 360, hole_count)\n    .hole(hole_dia)\n    .edges(\">Z or <Z or >X or <X or >Y or <Y\")\n    .fillet(10)\n)\n\n# Note: filleting on the top face is optional\n\n# Instead, fillet on the outer edge\nresult = (\n    cq.Workplane(\"XY\")"
    },
    {
      "prompt": "An L-shaped mounting bracket for a 3D printer motor, 50x50mm faces, 5mm thick, with 4 mounting holes for M3 screws.",
      "reference": "",
      "prediction": "import cadquery as cq\n\n# Dimensions\nlength = 50\nwidth = 50\nthickness = 5\nhole_diameter = 3.2  # clearance for M3 screws\nhole_offset = 10\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(length, thickness, width)\n    .faces(\">Z\")\n    .workplane(centerOption=\"CenterOfMass\")\n    .transformed(offset=(0, width/2 - thickness/2, 0), rotate=(0, 0, 90))\n    .box(length, thickness, width)\n    .faces(\">Z\")\n    .workplane()\n    # Holes on the first face\n    .pushPoints([\n        (hole_offset, thickness/2),\n        (length - hole_offset, thickness/2),\n        (hole_offset, -thickness/2),\n        (length - hole_offset, -thickness/2)\n    ])\n    .hole(hole_diameter)\n    .faces(\">Y\")\n    .workplane(centerOption=\"CenterOfMass\")\n    .pushPoints([\n        (hole_offset, thickness/2),\n        (length - hole_offset, thickness/2),\n        (hole_offset, -thickness/2),\n        (length - hole_offset, -thickness/2)\n    ])\n    .hole(hole_diameter)\n)\n\n# CadQuery doesn't have built-in transforms for 90 degree rotated faces, so we use a workaround\n# Here, we create the second face by rotating and translating a box, then combine both faces\n\n# Workaround: create second face manually\nsecond_face = (\n    cq.Workplane(\"XY\")\n    .box(length, thickness, width)\n    .translate((0, width/2, 0))\n    .rotate((0, 0, 0), (0, 0, 1), 90)\n    .translate((0, 0, width/2))\n)\n\nresult = result.union(second_face)\n\n# Hollow out the center\nresult = result.faces(\">Z\").workplane().rect(length - 20, width - 20, forConstruction=True).vertices().hole(15)\n\n# Chamfer edges\nresult = result.edges(\">Z or <Z\").chamfer(2)\n\n# Cut inner holes for mounting holes on second face\nresult = result.faces(\">Y\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Cut inner holes for mounting holes on first face\nresult = result.faces(\">Z\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Chamfer inner holes\nresult = result.edges(\">Z or <Z\").chamfer(1)\n\n# Fillet edges\nresult = result.edges(\">Z or <Z or >Y or <Y\").fillet(2)\n\n# Cut inner holes for mounting holes on second face\nresult = result.faces(\">Y\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Cut inner holes for mounting holes on first face\nresult = result.faces(\">Z\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Chamfer inner holes\nresult = result.edges(\">Z or <Z or >Y or <Y\").chamfer(1)\n\n# Fillet edges\nresult = result.edges(\">Z or <Z or >Y or <Y\").fillet(2)\n\n# Cut inner holes for mounting holes on second face\nresult = result.faces(\">Y\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Cut inner holes for mounting holes on first face\nresult = result.faces(\">Z\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Chamfer inner holes\nresult = result.edges(\">Z or <Z or >Y or <Y\").chamfer(1)\n\n# Fillet edges\nresult = result.edges(\">Z or <Z or >Y or <Y\").fillet(2)\n\n# Cut inner holes for mounting holes on second face\nresult = result.faces(\">Y\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Cut inner holes for mounting holes on first face\nresult = result.faces(\">Z\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Chamfer inner holes\nresult = result.edges(\">Z or <Z or >Y or <Y\").chamfer(1)\n\n# Fillet edges\nresult = result.edges(\">Z or <Z or >Y or <Y\").fillet(2)\n\n# Cut inner holes for mounting holes on second face\nresult = result.faces(\">Y\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Cut inner holes for mounting holes on first face\nresult = result.faces(\">Z\").workplane(centerOption=\"CenterOfMass\").pushPoints([\n    (hole_offset, thickness/2),\n    (length - hole_offset, thickness/2),\n    (hole_offset, -thickness/2),\n    (length - hole_offset, -thickness/2)\n]).hole(hole_diameter, depth=thickness + 1)\n\n# Chamfer inner holes\nresult = result.edges(\">Z or <Z or >Y or <Y\").chamfer(1)\n\n# Fillet edges\nresult = result.edges(\">Z or <Z or >Y or <Y\").fillet(2)"
    },
    {
      "prompt": "A factory layout section with two parallel 5000mm long conveyor belts spaced 2000mm apart, represented as long rectangular blocks.",
      "reference": "",
      "prediction": "import cadquery as cq\n\n# Parameters\nlength = 5000\nwidth = 20\nheight = 40\nspacing = 2000\n\n# Create one belt\nbelt = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n)\n\n# Create both belts by placing them side by side\nresult = (\n    cq.Assembly()\n    .add(belt, name=\"belt1\", loc=cq.Location((0, 0, 0)))\n    .add(belt, name=\"belt2\", loc=cq.Location((spacing, 0, 0)))\n)\n\n# Export to STL\nresult = result.toCompound()\n\n# Clean up faces to get one solid block\nresult = result.faces(\">Z\").workplane().rect(length + spacing, width, forConstruction=True).vertices().combine()\nresult = result.edges(\">Z\").fillet(2)\n\nresult = result.val()\n\n# Hollow out the block\nresult = (\n    result.faces(\">Z\").workplane().rect(length + spacing, width).cutThruAll()\n)\n\nresult = result\n\n# Export result\n# result.export(\"factory_layout.stl\")\n\n# Show result in browser\nresult\n\n# Or export as single STL\nresult.toStl(\"factory_layout.stl\")\n\n# Or as single PDF\nresult.toPdf(\"factory_layout.pdf\")\n\n# Or as single SVG\nresult.toSvg(\"factory_layout.svg\")\n\n# Or as single JPG\nresult.toJpg(\"factory_layout.jpg\")\n\n# Or as single PNG\nresult.toPng(\"factory_layout.png\")\n\n# Or as single BMP\nresult.toBmp(\"factory_layout.bmp\")\n\n# Or as single PLT\nresult.toPlt(\"factory_layout.plt\")\n\n# Or as single DXF\nresult.toDxf(\"factory_layout.dxf\")\n\n# Or as single OBJ\nresult.toObj(\"factory_layout.obj\")\n\n# Or as single NPZ\nresult.toNpz(\"factory_layout.npz\")\n\n# Or as single JSON\nresult.toJson(\"factory_layout.json\")\n\n# Or as single IGES\nresult.toIges(\"factory_layout.iges\")\n\n# Or as single ICS\nresult.toIcs(\"factory_layout.ics\")\n\n# Or as single SEP\nresult.toSep(\"factory_layout.sep\")\n\n# Or as single VTK\nresult.toVtk(\"factory_layout.vtk\")\n\n# Or as single STL (binary)\nresult.toStl(\"factory_layout.stl\")\n\n# Or as single STL (ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"ascii\")\n\n# Or as single STL (pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"pretty\")\n\n# Or as single STL (non-destructive)\nresult.toStl(\"factory_layout.stl\", mode=\"non-destructive\")\n\n# Or as single STL (non-destructive, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"non-destructive\", pretty=True)\n\n# Or as single STL (non-destructive, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"non-destructive\", ascii=True)\n\n# Or as single STL (non-destructive, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"non-destructive\", pretty=True, ascii=True)\n\n# Or as single STL (binary, compressed)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True)\n\n# Or as single STL (binary, compressed, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True)\n\n# Or as single STL (binary, compressed, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, ascii=True)\n\n# Or as single STL (binary, compressed, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True, ascii=True)\n\n# Or as single STL (binary, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True)\n\n# Or as single STL (binary, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", ascii=True)\n\n# Or as single STL (binary, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True, ascii=True)\n\n# Or as single STL (binary, compressed)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True)\n\n# Or as single STL (binary, compressed, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True)\n\n# Or as single STL (binary, compressed, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, ascii=True)\n\n# Or as single STL (binary, compressed, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True, ascii=True)\n\n# Or as single STL (binary)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\")\n\n# Or as single STL (binary, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True)\n\n# Or as single STL (binary, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", ascii=True)\n\n# Or as single STL (binary, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True, ascii=True)\n\n# Or as single STL (binary, compressed)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True)\n\n# Or as single STL (binary, compressed, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True)\n\n# Or as single STL (binary, compressed, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, ascii=True)\n\n# Or as single STL (binary, compressed, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True, ascii=True)\n\n# Or as single STL (binary)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\")\n\n# Or as single STL (binary, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True)\n\n# Or as single STL (binary, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", ascii=True)\n\n# Or as single STL (binary, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", pretty=True, ascii=True)\n\n# Or as single STL (binary, compressed)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True)\n\n# Or as single STL (binary, compressed, pretty)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True)\n\n# Or as single STL (binary, compressed, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, ascii=True)\n\n# Or as single STL (binary, compressed, pretty, ASCII)\nresult.toStl(\"factory_layout.stl\", mode=\"binary\", compressed=True, pretty=True, ascii=True)\n\n# Or as"
    },
    {
      "prompt": "A spur gear with 24 teeth, a pitch diameter of 60mm, and a 10mm central bore with a 3mm keyway.",
      "reference": "",
      "prediction": "import cadquery as cq\n\n# Parameters\nnum_teeth = 24\npitch_diameter = 60  # mm\npressure_angle = 20  # degrees\nmodule = pitch_diameter / num_teeth  # mm\nkeyway_width = 3  # mm\nkeyway_depth = 2  # mm\nbore_diameter = 10  # mm\n\n# Base circle radius\nbase_radius = (pitch_diameter / 2) * cq.cos(cq.radians(pressure_angle))\n\n# Addendum and dedendum\naddendum = module\ndedendum = 1.25 * module\n\n# Outer diameter and root diameter\nouter_diameter = pitch_diameter + 2 * addendum\nroot_diameter = pitch_diameter - 2 * dedendum\n\n# Create a single tooth profile using involute approximation\n# For simplicity, approximate tooth as a trapezoid\n\n# Tooth thickness at pitch circle (circular pitch / 2)\ncircular_pitch = cq.pi * module\ntooth_thickness = circular_pitch / 2\n\n# Tooth base and tip widths\nbase_width = tooth_thickness * 0.7\ntip_width = tooth_thickness * 0.9\n\n# Create 2D tooth profile\ntooth_profile = (\n    cq.Workplane(\"XY\")\n    .polyline([\n        (base_width / 2, root_diameter / 2),\n        (tip_width / 2, root_diameter / 2),\n        (tip_width / 2, outer_diameter / 2),\n        (base_width / 2, outer_diameter / 2),\n        (base_width / 2, root_diameter / 2),\n    ])\n    .close()\n)\n\n# Create gear blank\ngear_blank = (\n    cq.Workplane(\"XY\")\n    .circle(root_diameter / 2)\n    .extrude(15)  # thickness\n)\n\n# Create one tooth\ntooth_3d = (\n    tooth_profile\n    .extrude(10)  # tooth height\n)\n\n# Create all teeth by polar array\nteeth = tooth_3d\nfor i in range(1, num_teeth):\n    teeth = teeth.union(tooth_3d.rotate((0, 0, 0), (0, 0, 1), 360 / num_teeth * i))\n\n# Create keyway\nkeyway = (\n    cq.Workplane(\"XY\")\n    .rect(keyway_width, keyway_depth)\n    .extrude(5)\n    .translate((bore_diameter / 2, 0, 10))\n)\n\n# Combine gear blank with teeth\ngear = gear_blank.union(teeth)\n\n# Cut central bore\nresult = gear.faces(\">Z\").workplane().hole(bore_diameter)\n\n# Cut keyway with keyway depth\nresult = result.cut(keyway)\n\n# Result\nresult.show()\n\n# Export STL\nresult.export('result.stl')\n\n# Print gear parameters\nprint(\"Gear parameters:\")\nprint(f\"Num teeth: {num_teeth}\")\nprint(f\"Pitch diameter: {pitch_diameter} mm\")\nprint(f\"Pressure angle: {pressure_angle} degrees\")\nprint(f\"Module: {module} mm\")\nprint(f\"Outer diameter: {outer_diameter} mm\")\nprint(f\"Root diameter: {root_diameter} mm\")\nprint(f\"Bore diameter: {bore_diameter} mm\")\n\n# Visualize keyway\n# keyway.show()\n\n# Visualize tooth profile\n# tooth_profile.extrude(10).show()\n\n# Visualize teeth\n# teeth.show()\n\n# Visualize gear blank\n# gear_blank.extrude(15).faces(\">Z\").workplane().hole(bore_diameter).show()\n\n# Visualize combined gear\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Visualize combined gear with keyway cut\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).export('result.stl')\n\n# Export combined gear\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).export('result.stl')\n\n# Export gear blank\n# gear_blank.extrude(15).show()\n\n# Export teeth\n# teeth.extrude(10).show()\n\n# Export combined gear with teeth\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export combined gear with teeth and keyway cut\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).show()\n\n# Export combined gear with teeth, keyway cut, and central bore\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).faces(\">Z\").workplane().hole(bore_diameter).show()\n\n# Export combined gear with teeth, keyway cut, and central bore\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).faces(\">Z\").workplane().hole(bore_diameter).export('result.stl')\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).faces(\">Z\").workplane().hole(bore_diameter).export('result.stl')\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).faces(\">Z\").workplane().hole(bore_diameter).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).cut(keyway).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).export('result.stl')\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()\n\n# Export\n# (gear_blank.extrude(15).union(teeth)).show()"
    },
    {
      "prompt": "A parametric enclosure for electronics, 120x80x40mm, with 2mm walls, a recessed lip for a lid, and four internal mounting standoffs.",
      "reference": "",
      "prediction": "import cadquery as cq\n\n# Outer dimensions\nlength = 120\nwidth = 80\nheight = 40\nwall_thickness = 2\nlid_recess_depth = 3\n\n# Internal mounting standoff parameters\nstandoff_diameter = 5\nstandoff_height = 15\nstandoff_offset = 10\n\nresult = (\n    cq.Workplane(\"XY\")\n    # Create outer box\n    .box(length, width, height)\n    # Hollow out the box to create walls\n    .faces(\">Z\")\n    .workplane()\n    .rect(length - 2*wall_thickness, width - 2*wall_thickness, forConstruction=True)\n    .rect(length - 2*wall_thickness, width - 2*wall_thickness)\n    .cutThruAll()\n    # Create lid recess on top face\n    .faces(\">Z\")\n    .workplane()\n    .rect(length - 2*wall_thickness, width - 2*wall_thickness)\n    .extrude(-lid_recess_depth)\n    # Add internal mounting standoffs\n    .faces(\"<Z\")\n    .workplane(offset=wall_thickness)\n    .pushPoints([\n        (standoff_offset, standoff_offset),\n        (length - standoff_offset, standoff_offset),\n        (standoff_offset, width - standoff_offset),\n        (length - standoff_offset, width - standoff_offset)\n    ])\n    .cylinder(standoff_height, standoff_diameter / 2)\n)\n\n# Note: CadQuery does not have built-in standoff mounting helper, so above is a simplified example\n\n# Display result\nresult.show()\n\n# Export to STL\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load(\"enclosure.cadquery\")\nresult.show()\n\n# Exported result\nresult.export(\"enclosure.stl\")\n\n# Or save to a single file\nresult.save(\"enclosure.cadquery\")\n\n# Load result from file\nresult = cq.Workplane(\"XY\").load"
    },
    {
      "prompt": "A heat sink with a base of 100x100x5mm and 20 vertical fins that are 20mm high and 2mm thick.",
      "reference": "",
      "prediction": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .box(100, 100, 5)\n    .faces(\">Z\")\n    .workplane()\n    .rect(100, 20, forConstruction=True)\n    .vertices()\n    .rect(2, 20)\n    .extrude(20)\n)\n\n# Note: CadQuery's built-in heat sink pattern is complex, so this example is simple\n\n# Base heat sink\nbase = cq.Workplane(\"XY\").box(100, 100, 5)\n\n# Heat sink fin profile\nfin = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=2.5)\n    .rect(2, 20)\n    .extrude(20)\n)\n\n# Position fins around the heat sink\nfins = cq.Workplane(\"XY\")\nfor x in range(-80, 81, 40):\n    for y in [-40, 40]:\n        fins = fins.union(fin.translate((x, y, 5)))\n\nresult = base.union(fins)\n\n# Cut heat sink bottom to ensure fin base\nresult = result.faces(\"<Z\").workplane().rect(90, 90, forConstruction=True).offset2D(1).cutThruAll()\n\n# Add small hole in center for coolant\nresult = result.faces(\">Z\").workplane().hole(8)\n\n# Add fillet to fins\nresult = result.edges(\">Z and |Z\").fillet(1)\n\n# Add chamfer to base edges\nresult = result.edges(\">Z and |X or |Y\").chamfer(1)\n\n# Add rounded corners to base\nresult = result.edges(\">Z and |X or |Y\").fillet(1)\n\n# Add fillet to base\nresult = result.edges(\">Z\").fillet(1)\n\n# Cut inner corner for base\nresult = result.faces(\">Z\").workplane().rect(90, 90, forConstruction=True).cutThruAll()\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cutBlind(-2)\n\n# Add inner cut for heat sink bottom\nresult = result.faces(\"<Z\").workplane().rect(90, 90).cut"
    },
    {
      "prompt": "A circular flange with an outer diameter of 200mm, inner diameter of 100mm, 15mm thick, and 8 bolt holes (dia 12mm) on a 160mm bolt circle.",
      "reference": "",
      "prediction": "import cadquery as cq\n\nresult = (\n    cq.Workplane(\"XY\")\n    .circle(100)  # Inner diameter radius\n    .circle(100)  # Inner diameter circle\n    .circle(100)  # Just for clarity\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner diameter\n    .circle(100)  # Clarify inner"
    },
    {
      "prompt": "A complex 3D shape created by lofting a 20mm square at Z=0 to a 40mm circle at Z=50.",
      "reference": "",
      "prediction": "import cadquery as cq\n\n# Create the base profile (square)\nbase = (\n    cq.Workplane(\"XY\")\n    .rect(20, 20)\n    .extrude(5)\n)\n\n# Create the top profile (circle)\ntop = (\n    cq.Workplane(\"XY\")\n    .circle(20)\n    .extrude(50)\n)\n\n# Loft between two profiles\nresult = base.loft(top)\n\n# Visualize result\nresult.show()\n\n# Export to STL\nresult.export(\"lofted_shape.stl\")\n\n# Note: CadQuery's loft() method automatically interpolates between profiles,\n# so there is no need to create intermediate shapes in this example.\n\n# For more complex shapes, it may be necessary to create intermediate shapes explicitly.\n\n# For example, to create a lofted shape with a 20mm square base, a 30mm step, and a 40mm circle top:\n\n# Base profile\nbase = (\n    cq.Workplane(\"XY\")\n    .rect(20, 20)\n    .extrude(5)\n)\n\n# Intermediate step 1 (30mm diameter)\nstep1 = (\n    cq.Workplane(\"XY\")\n    .circle(15)\n    .extrude(30)\n)\n\n# Intermediate step 2 (30mm diameter)\nstep2 = (\n    cq.Workplane(\"XY\")\n    .circle(20)\n    .extrude(30)\n)\n\n# Combine base and steps\nresult = base.union(step1).union(step2)\n\nresult.show()\n\n# Export to STL\nresult.export(\"complex_lofted_shape.stl\")\n\n# Note: CadQuery's loft() method automatically interpolates between profiles,\n# so this complex shape can be created with a single loft, but here we show\n# how to create the shape manually for demonstration.\n\n# For reference, here is the lofted shape using CadQuery's loft():\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .rect(20, 20)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"lofted_shape_manual.stl\")\n\n# Since CadQuery's loft() method automatically interpolates, we can use a simplified shape for this example:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .circle(10)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"simplified_lofted_shape.stl\")\n\n# Note: In this simplified example, the loft creates a smooth cylindrical shape between two circles,\n# but for realistic shapes, using a loft with multiple steps may be necessary.\n\n# For example, to create a lofted shape with a 20mm square base, a 30mm step, and a 40mm circle top, using multiple lofts:\n\n# Base profile\nbase = (\n    cq.Workplane(\"XY\")\n    .rect(20, 20)\n    .extrude(5)\n)\n\n# Step 1 (30mm diameter)\nstep1 = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=5)\n    .circle(15)\n    .extrude(30)\n)\n\n# Step 2 (30mm diameter)\nstep2 = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=35)\n    .circle(20)\n    .extrude(30)\n)\n\n# Combine base and steps\nresult = base.union(step1).union(step2)\n\nresult.show()\n\n# Export to STL\nresult.export(\"complex_lofted_shape_multi_step.stl\")\n\n# Note: In this example, the steps are added manually, but in reality, the steps should be interpolated automatically.\n# For example, using the CadQuery loft() method:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .rect(20, 20)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"lofted_shape_manual_multi_step.stl\")\n\n# Since CadQuery's loft() method automatically interpolates, we can use a simplified shape for this example:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .circle(10)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"simplified_lofted_shape_multi_step.stl\")\n\n# Note: In this simplified example, the loft creates a smooth cylindrical shape between two circles,\n# but for realistic shapes, using a loft with multiple steps may be necessary.\n\n# For example, to create a lofted shape with a 20mm square base, a 30mm step, and a 40mm circle top, using multiple lofts:\n\n# Base profile\nbase = (\n    cq.Workplane(\"XY\")\n    .rect(20, 20)\n    .extrude(5)\n)\n\n# Step 1 (30mm diameter)\nstep1 = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=5)\n    .circle(15)\n    .extrude(30)\n)\n\n# Step 2 (30mm diameter)\nstep2 = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=35)\n    .circle(20)\n    .extrude(30)\n)\n\n# Combine base and steps\nresult = base.union(step1).union(step2)\n\nresult.show()\n\n# Export to STL\nresult.export(\"complex_lofted_shape_multi_step.stl\")\n\n# Note: In this example, the steps are added manually, but in reality, the steps should be interpolated automatically.\n# For example, using the CadQuery loft() method:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .rect(20, 20)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"lofted_shape_manual_multi_step.stl\")\n\n# Since CadQuery's loft() method automatically interpolates, we can use a simplified shape for this example:\n\nresult = (\n    cq.Workplane(\"XY\")\n    .workplane(offset=0)\n    .circle(10)\n    .extrude(5)\n    .workplane(offset=50)\n    .circle(20)\n    .loft(combine=True)\n)\n\nresult.show()\n\n# Export to STL\nresult.export(\"simplified_lofted_shape_multi_step.stl\")\n\n# Note: In this simplified example, the loft creates a smooth cylindrical shape between two circles,\n# but for realistic shapes, using a loft with multiple steps may be necessary.\n\n# For example, to create a lofted shape with a 20mm square base, a 30mm step, and a 40mm circle top,"
    }
  ]
}